export const tokens = {
  color: {
    bg:           '#F5F5F5',
    surface:      '#FFFFFF',
    border:       '#E0E0E0',
    divider:      '#EEEEEE',
    text:         '#1A1A1A',
    textSecondary:'#6B6B6B',
    textDisabled: '#BDBDBD',
    primary:      '#2563EB',
    primaryHover: '#1D4ED8',
    primaryText:  '#FFFFFF',
    secondary:    '#7C3AED',
    success:      '#16A34A',
    warning:      '#D97706',
    error:        '#DC2626',
    placeholder:  '#D1D5DB',
  },
  space: {
    xs:  4,
    sm:  8,
    md:  16,
    lg:  24,
    xl:  40,
    xxl: 64,
  },
  radius: {
    sm:   4,
    md:   8,
    lg:   16,
    full: 9999,
  },
  font: {
    family: 'system-ui, -apple-system, sans-serif',
    size: {
      xs:  11,
      sm:  12,
      md:  14,
      lg:  16,
      xl:  20,
      xxl: 28,
      xxxl:36,
    },
    weight: {
      normal: 400,
      medium: 500,
      semibold: 600,
      bold:   700,
    },
    lineHeight: {
      tight:  1.2,
      normal: 1.5,
      loose:  1.8,
    },
  },
  shadow: {
    sm: '0 1px 2px rgba(0,0,0,0.06)',
    md: '0 2px 8px rgba(0,0,0,0.08)',
    lg: '0 4px 16px rgba(0,0,0,0.10)',
  },
  transition: 'all 0.15s ease',
}
